### ISSUE TITLE
What is estimated training time for LDA model ?

### ISSUE THREAD

**Issue by tim5go** [BoPengGit/LDA-Doc2Vec-example-with-PCA-LDAvis-visualization#2]
As titled, what is the expected training time for LDA model (with default setting) ?

**Comment by BoPengGit** [comment]
Hi Tim,

I'm not sure, this was a while ago. I think for me using gensim's multicore function for LDA on 1-10 million lines of catalog text took a day or more on aws cpu server. I think you just have to run it and see for yourself.

Sorry if that wasn't helpful Tim!
